"""
P-MCP + Grok (xAI) Agent Example
==================================
Demonstrates Grok commanding a physical robot arm through P-MCP with
full shadow-validated safety — no hardware required to run this demo.

Architecture:
    Grok LLM (xAI API)
         │  tool_use (OpenAI-compatible)
         ▼
    GrokAgent  ← this file
         │  discover tools (actuations/list)
         │  shadow preview before any call
         │  call actuation (tools/call)
         ▼
    PMCPServer (in-process, simulated UR5e arm)
         │  Constitution → Shadow → TEE Gate
         ▼
    Simulated hardware (no real robot needed)

Usage:
    # With real xAI Grok API:
    export XAI_API_KEY=xai-...
    python examples/example_grok_agent.py

    # Without API key (dry-run, shows what Grok WOULD do):
    python examples/example_grok_agent.py --dry-run

    # Target a remote P-MCP server over HTTP:
    python examples/example_grok_agent.py --server http://my-robot:8081

Requirements:
    pip install openai          # xAI uses the OpenAI-compatible SDK
    pip install cryptography    # for TEE / safety constitution
"""
from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import sys
import time
from typing import Any, Dict, List, Optional

# ── path setup (works whether run as script or module) ──────────────────────
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

log = logging.getLogger("pmcp.grok_example")
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(name)-28s  %(message)s",
    datefmt="%H:%M:%S",
    stream=sys.stderr,
)


# ─────────────────────────────────────────────────────────────────────────────
#  P-MCP imports
# ─────────────────────────────────────────────────────────────────────────────
from v05.pmcp_v5_server import PMCPServer
from v05.pmcp_v5_client import PMCPClient, PMCPClientError
from v05.pmcp_v5_types  import ActuationResult, SensorReading, SensorType
from v05.robot_servers.arm_server import build_arm_server


# ─────────────────────────────────────────────────────────────────────────────
#  Grok client wrapper (xAI OpenAI-compatible API)
# ─────────────────────────────────────────────────────────────────────────────

class GrokClient:
    """
    Thin wrapper around the xAI Grok API using the OpenAI-compatible SDK.

    Grok-2 / Grok-3 supports function calling (tool_use) identically to
    GPT-4o — P-MCP tool schemas generated by `to_llm_schema()` work
    without modification.
    """

    # xAI API base URL (OpenAI-compatible)
    BASE_URL = "https://api.x.ai/v1"
    DEFAULT_MODEL = "grok-3"

    def __init__(self, api_key: Optional[str] = None, model: str = DEFAULT_MODEL):
        self.model   = model
        self.api_key = api_key or os.environ.get("XAI_API_KEY", "")
        self._client = None

        if self.api_key:
            try:
                import openai  # pip install openai
                self._client = openai.AsyncOpenAI(
                    api_key=self.api_key,
                    base_url=self.BASE_URL,
                )
                log.info(f"GrokClient: using {self.model} via xAI API")
            except ImportError:
                log.warning("openai package not installed — run: pip install openai")
        else:
            log.info("GrokClient: no API key — dry-run mode (simulated responses)")

    async def plan(
        self,
        mission: str,
        tools: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """
        Ask Grok to plan the mission and return a list of tool calls.

        Returns: list of {"name": str, "arguments": dict} dicts.
        Dry-run: returns a deterministic simulated plan.
        """
        if self._client is None:
            return self._simulate_plan(mission, tools)

        system_prompt = (
            "You are an expert robotics mission planner using the P-MCP protocol. "
            "Your job is to safely complete the given mission by calling the provided "
            "robot actuations in the correct order. "
            "Always prefer lower speeds for safety. "
            "Do NOT call the same actuation more than 3 times in a row. "
            "Return ONLY the tool calls needed; no prose."
        )

        # Convert P-MCP tool schemas to OpenAI function format
        openai_tools = [
            {
                "type": "function",
                "function": {
                    "name":        t["name"],
                    "description": t.get("description", ""),
                    "parameters":  t.get("inputSchema", {}),
                },
            }
            for t in tools
        ]

        messages = [
            {"role": "system",  "content": system_prompt},
            {"role": "user",    "content": f"Mission: {mission}"},
        ]

        tool_calls_result: List[Dict[str, Any]] = []

        # Agentic loop: Grok calls tools, we collect them (no hardware yet)
        for _step in range(10):  # max 10 planning steps
            response = await self._client.chat.completions.create(
                model=self.model,
                messages=messages,
                tools=openai_tools,
                tool_choice="auto",
                temperature=0.1,   # low temperature for deterministic planning
            )

            choice = response.choices[0]

            if choice.finish_reason == "tool_calls" and choice.message.tool_calls:
                for tc in choice.message.tool_calls:
                    fn   = tc.function
                    args = json.loads(fn.arguments) if fn.arguments else {}
                    tool_calls_result.append({"name": fn.name, "arguments": args})
                    log.info(f"  Grok planned: {fn.name}({args})")

                # Feed the planned calls back as "assistant" context
                messages.append({"role": "assistant", "content": None,
                                  "tool_calls": choice.message.tool_calls})
                # Acknowledge each call with a placeholder result
                for tc in choice.message.tool_calls:
                    messages.append({
                        "role":         "tool",
                        "tool_call_id": tc.id,
                        "content":      json.dumps({"queued": True}),
                    })

            else:
                # Grok said stop / no more tools
                break

        return tool_calls_result

    # ── Dry-run fallback ─────────────────────────────────────────────────────

    def _simulate_plan(
        self, mission: str, tools: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """
        Deterministic simulated Grok plan for testing without an API key.
        Mimics what Grok-3 would produce for a pick-and-place mission.
        """
        tool_names = {t["name"] for t in tools}

        plan: List[Dict[str, Any]] = []

        if "home_position" in tool_names:
            plan.append({"name": "home_position", "arguments": {}})

        if "move_to" in tool_names:
            # Pick approach
            plan.append({"name": "move_to",
                         "arguments": {"x": 0.4, "y": 0.0, "z": 0.3, "speed": 0.2}})
            # Lower to object
            plan.append({"name": "move_to",
                         "arguments": {"x": 0.4, "y": 0.0, "z": 0.12, "speed": 0.1}})

        if "gripper_close" in tool_names:
            plan.append({"name": "gripper_close", "arguments": {"force_n": 20.0}})

        if "move_to" in tool_names:
            # Lift
            plan.append({"name": "move_to",
                         "arguments": {"x": 0.4, "y": 0.0, "z": 0.35, "speed": 0.2}})
            # Move to place
            plan.append({"name": "move_to",
                         "arguments": {"x": -0.3, "y": 0.3, "z": 0.35, "speed": 0.3}})
            # Lower to place
            plan.append({"name": "move_to",
                         "arguments": {"x": -0.3, "y": 0.3, "z": 0.12, "speed": 0.1}})

        if "gripper_open" in tool_names:
            plan.append({"name": "gripper_open", "arguments": {}})

        if "home_position" in tool_names:
            plan.append({"name": "home_position", "arguments": {}})

        log.info(f"  [Dry-run] Simulated {len(plan)}-step Grok plan")
        return plan


# ─────────────────────────────────────────────────────────────────────────────
#  GrokAgent: P-MCP + Grok planning loop
# ─────────────────────────────────────────────────────────────────────────────

class GrokAgent:
    """
    Connects Grok to a P-MCP server and executes the LLM-planned mission
    with full safety pipeline:
        1. Shadow preview → block unsafe trajectories BEFORE execution
        2. Safety constitution → enforce ISO 10218 hard rules
        3. Execute → hardware (or simulation)

    Works with any P-MCP server: in-process, stdio, or remote HTTP.
    """

    def __init__(
        self,
        grok: GrokClient,
        server: Optional[PMCPServer] = None,
        server_url: Optional[str]    = None,
    ):
        self.grok       = grok
        self.server     = server
        self.server_url = server_url

    async def run_mission(self, mission: str) -> None:
        print(f"\n{'═'*70}")
        print(f"  GROK → P-MCP MISSION")
        print(f"  Mission: {mission}")
        print(f"{'═'*70}")

        async with PMCPClient("grok-agent") as client:
            # ── 1. Connect to the P-MCP server ────────────────────────────
            if self.server:
                await client.connect_server(self.server)
            elif self.server_url:
                await client.connect_http(self.server_url)
            else:
                raise ValueError("Provide either server= or server_url=")

            # ── 2. Discover robot capabilities ────────────────────────────
            tools   = await client.list_tools()
            sensors = await client.list_sensors()
            ident   = await client.get_identity()
            const   = await client.get_constitution()

            print(f"\n  Robot      : {ident['robot_id']} ({ident['robot_class']})")
            print(f"  DID        : {ident['did'][:32]}...")
            print(f"  Tools      : {[t['name'] for t in tools]}")
            print(f"  Sensors    : {[s['name'] for s in sensors]}")
            print(f"  Constitution: {const['rule_count']} rules  "
                  f"[{const['fingerprint'][:16]}...]")

            # ── 3. Ask Grok to plan the mission ───────────────────────────
            print(f"\n  Asking Grok to plan mission...")
            t0 = time.perf_counter()
            planned_calls = await self.grok.plan(mission, tools)
            t1 = time.perf_counter()

            print(f"  Grok returned {len(planned_calls)} tool calls "
                  f"in {(t1-t0)*1000:.0f}ms")

            if not planned_calls:
                print("  Grok produced no tool calls — mission complete (trivially).")
                return

            # ── 4. Execute each planned call through the safety pipeline ──
            print(f"\n  Executing with P-MCP safety pipeline...\n")
            results_summary = []

            for i, call in enumerate(planned_calls, 1):
                name = call["name"]
                args = call["arguments"]

                print(f"  [{i:02d}] {name}({args})")

                # 4a. Shadow preview BEFORE touching hardware
                try:
                    preview = await client.shadow_preview(name, args)
                    shadow_ok = preview.get("safe", False)
                    energy    = preview.get("energy_joules", 0.0)
                    risk      = preview.get("risk_score", 0.0)

                    if not shadow_ok:
                        reason = preview.get("reason", "unknown")
                        print(f"         ✗ SHADOW BLOCKED: {reason}")
                        results_summary.append((name, "blocked_shadow", reason))
                        continue

                    print(f"         ✓ shadow safe  "
                          f"[energy={energy:.1f}J  risk={risk:.2f}]")

                except PMCPClientError as e:
                    # Shadow not supported on this server — proceed anyway
                    log.debug(f"Shadow preview unavailable: {e}")

                # 4b. Execute (constitution + TEE gate enforced server-side)
                try:
                    result = await client.call_tool(name, args)
                    success = result.get("success", True)
                    output  = result.get("output", {})

                    if success:
                        print(f"         ✓ executed     output={output}")
                        results_summary.append((name, "ok", str(output)))
                    else:
                        reason = result.get("error", "unknown error")
                        print(f"         ✗ FAILED: {reason}")
                        results_summary.append((name, "failed", reason))

                except PMCPClientError as e:
                    code = e.code if hasattr(e, "code") else "ERR"
                    print(f"         ✗ ERROR [{code}]: {e}")
                    results_summary.append((name, f"error_{code}", str(e)))

            # ── 5. Mission summary ─────────────────────────────────────────
            ok      = sum(1 for _, s, _ in results_summary if s == "ok")
            blocked = sum(1 for _, s, _ in results_summary if "blocked" in s)
            failed  = sum(1 for _, s, _ in results_summary if s in ("failed",) or s.startswith("error"))

            print(f"\n{'─'*70}")
            print(f"  Mission complete: {ok} executed · {blocked} safety-blocked · {failed} failed")
            print(f"{'─'*70}\n")


# ─────────────────────────────────────────────────────────────────────────────
#  Demo missions
# ─────────────────────────────────────────────────────────────────────────────

async def demo_pick_and_place(dry_run: bool, server_url: Optional[str]) -> None:
    """
    Demo 1: Grok plans a pick-and-place and P-MCP validates safety.
    """
    grok   = GrokClient(model="grok-3")
    server = None if server_url else build_arm_server("ur5e-demo", "UR5e", "cell-A")

    agent = GrokAgent(grok=grok, server=server, server_url=server_url)
    await agent.run_mission(
        "Pick the red box at position (0.4, 0.0, 0.12) "
        "and place it at (-0.3, 0.3, 0.12). "
        "Go home after."
    )


async def demo_safety_rejection(dry_run: bool) -> None:
    """
    Demo 2: Grok tries to command an unsafe move; shadow preview blocks it.
    Shadow validator rejects Z < floor (negative Z = below ground).
    """
    grok   = GrokClient(model="grok-3")
    server = build_arm_server("ur5e-safety-test", "UR5e", "cell-B")

    print(f"\n{'═'*70}")
    print(f"  SAFETY DEMO: Attempting unsafe move (Z below floor)")
    print(f"{'═'*70}")

    async with PMCPClient("grok-safety-test") as client:
        await client.connect_server(server)

        unsafe_args = {"x": 0.5, "y": 0.0, "z": -0.15, "speed": 2.0}  # Z < 0 → blocked
        print(f"\n  Calling move_to({unsafe_args}) ...")

        try:
            preview = await client.shadow_preview("move_to", unsafe_args)
            if not preview.get("safe", True):
                print(f"  ✓ Shadow CORRECTLY BLOCKED: {preview.get('reason')}")
            else:
                # Try executing — constitution will block at the gate
                result = await client.call_tool("move_to", unsafe_args)
                print(f"  Result: {result}")
        except PMCPClientError as e:
            print(f"  ✓ P-MCP CORRECTLY REJECTED [{e.code}]: {e}")


async def demo_sensor_read(dry_run: bool) -> None:
    """
    Demo 3: Grok reads sensor data before planning.
    Shows how LLMs can query robot state via MCP Resources.
    """
    grok   = GrokClient(model="grok-3")
    server = build_arm_server("ur5e-sensor-demo", "UR5e", "cell-C")

    print(f"\n{'═'*70}")
    print(f"  SENSOR DEMO: Grok reads robot state before planning")
    print(f"{'═'*70}")

    async with PMCPClient("grok-sensor-test") as client:
        await client.connect_server(server)

        sensors = await client.list_sensors()
        print(f"\n  Available sensors: {[s['name'] for s in sensors]}")

        for sensor in sensors[:3]:  # read first 3 sensors
            try:
                reading = await client.read_sensor(sensor["name"])
                print(f"  {sensor['name']:30s} = {reading.get('value')} "
                      f"[{reading.get('unit', '')}]")
            except PMCPClientError as e:
                print(f"  {sensor['name']:30s}   (unavailable: {e})")

        # Now plan with sensor context
        print(f"\n  Grok plans based on current sensor state...")
        tools = await client.list_tools()
        plan  = await grok.plan(
            "The robot is at home. Move to (0.3, 0.1, 0.4) and read joint angles.",
            tools,
        )
        print(f"  Grok's {len(plan)}-step plan: "
              f"{[c['name'] for c in plan]}")


# ─────────────────────────────────────────────────────────────────────────────
#  Entry point
# ─────────────────────────────────────────────────────────────────────────────

async def main() -> None:
    parser = argparse.ArgumentParser(
        description="P-MCP + Grok (xAI) Agent Example",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Run without real Grok API key (simulated plan)",
    )
    parser.add_argument(
        "--server", metavar="URL", default=None,
        help="Connect to a remote P-MCP HTTP server (e.g. http://localhost:8081)",
    )
    parser.add_argument(
        "--demo",
        choices=["pick", "safety", "sensors", "all"],
        default="all",
        help="Which demo to run (default: all)",
    )
    args = parser.parse_args()

    if not args.dry_run and not os.environ.get("XAI_API_KEY"):
        print(
            "\n  NOTE: XAI_API_KEY not set — running in dry-run mode.\n"
            "        Set export XAI_API_KEY=xai-... for real Grok responses.\n"
        )
        args.dry_run = True

    demos = args.demo if args.demo != "all" else ["pick", "safety", "sensors"]
    if isinstance(demos, str):
        demos = [demos]

    for demo_name in demos:
        if demo_name == "pick":
            await demo_pick_and_place(args.dry_run, args.server)
        elif demo_name == "safety":
            await demo_safety_rejection(args.dry_run)
        elif demo_name == "sensors":
            await demo_sensor_read(args.dry_run)


if __name__ == "__main__":
    asyncio.run(main())
